# Generated by Django 4.2.6 on 2023-10-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_category_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='color',
            field=models.CharField(max_length=124, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='icon',
            field=models.CharField(max_length=124, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='color',
            field=models.CharField(max_length=124, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='icon',
            field=models.CharField(max_length=124, null=True),
        ),
    ]
