# Generated by Django 4.2.7 on 2023-11-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0004_alter_transaction_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='icon',
            field=models.IntegerField(null=True),
        ),
    ]
