# Generated by Django 4.2.7 on 2023-11-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0005_alter_transaction_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='icon',
            field=models.IntegerField(default=47),
            preserve_default=False,
        ),
    ]
